# This file was generated by GoReleaser. DO NOT EDIT.
class Dirin < Formula
  desc ""
  homepage ""
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lhopki01/dirin/releases/download/v0.1.4/dirin_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "e8f26bdf0a905c3ee1328ab925c7b6ac3021832b295afe7580df0ecb9fceb918"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lhopki01/dirin/releases/download/v0.1.4/dirin_0.1.4_Linux_x86_64.tar.gz"
      sha256 "b53201dc8521b9c2d0889bc4a07102d6c43c70548b5b8c311e6f652e27503415"
    end
  end

  def install
    bin.install "dirin"
  end
end
