# This file was generated by GoReleaser. DO NOT EDIT.
class DockerChainBuilder < Formula
  desc "Tool to build multiple dependent docker images in the correct order"
  homepage ""
  version "1.1.10"

  if OS.mac?
    url "https://github.com/lhopki01/docker-chain-builder/releases/download/v1.1.10/docker-chain-builder_1.1.10_Darwin_x86_64.tar.gz"
    sha256 "83f5a10e374b5c84e8baebc74411b3eecad0a0506596ba89cfc654c345581c72"
  elsif OS.linux?
    url "https://github.com/lhopki01/docker-chain-builder/releases/download/v1.1.10/docker-chain-builder_1.1.10_Linux_x86_64.tar.gz"
    sha256 "a5e676e1e002dfb5d5dbfeb081d3baf366e55dc71f914e1bb408a94132850428"
  end
  
  depends_on "docker"

  def install
    bin.install "docker-chain-builder"
  end
end
