# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitMassSync < Formula
  desc "Tool to keep multiple local repos in sync with github"
  homepage "https://github.com/lhopki01/git-mass-sync"
  version "2.5.2"

  depends_on "git"
  depends_on "hub"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/lhopki01/git-mass-sync/releases/download/v2.5.2/git-mass-sync_2.5.2_Darwin_arm64.tar.gz"
      sha256 "aa88bf5acbbadb1897cf8b940ac01c27ebf4ac57d1dbe1be2745094fdd683bd3"

      def install
        bin.install "git-mass-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lhopki01/git-mass-sync/releases/download/v2.5.2/git-mass-sync_2.5.2_Darwin_x86_64.tar.gz"
      sha256 "99fa23941af64d6b3fa1a4eae82f846459805bf021035783ada87b302f8abccc"

      def install
        bin.install "git-mass-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lhopki01/git-mass-sync/releases/download/v2.5.2/git-mass-sync_2.5.2_Linux_arm64.tar.gz"
      sha256 "09c4e245716772ef5a1a68c8c784c38bee9ea74759fbdc4f504415a7703ef501"

      def install
        bin.install "git-mass-sync"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lhopki01/git-mass-sync/releases/download/v2.5.2/git-mass-sync_2.5.2_Linux_x86_64.tar.gz"
      sha256 "fe0ffb25b76465497f7e339f1bb1e6b2b0b036fa25c6edb76b53ff98c15586e2"

      def install
        bin.install "git-mass-sync"
      end
    end
  end
end
