# This file was generated by GoReleaser. DO NOT EDIT.
class KubernetesJobUi < Formula
  desc ""
  homepage ""
  version "0.3.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/lhopki01/kubernetes-job-ui/releases/download/v0.3.0/kubernetes-job-ui_0.3.0_Darwin_x86_64.tar.gz"
    sha256 "d703ea6b807c0f63cd3017b4da369d791a4ac3cc77369a81c570bc0f4e23e241"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/lhopki01/kubernetes-job-ui/releases/download/v0.3.0/kubernetes-job-ui_0.3.0_Linux_x86_64.tar.gz"
      sha256 "4eac0b5519c79d65d73ebcf2e8ffb3a8402f852000d58a2ac5e58d7caccdaece"
    end
  end

  def install
    bin.install "kubernetes-job-ui"
  end
end
